### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by 99991** [likejazz/llama3.np#1]
You can improve the performance of the tokenizer by using Python's `heappush` and `heappop` functions. For example, see this tokenizer for my simplified TinyLlama implementation: https://github.com/99991/SimpleTinyLlama/blob/9af6f7df6e12d8478a90d3cd5c8e8c1a95fce0fe/tokenizer.py#L96

Instead of [silencing warnings](https://github.com/likejazz/llama3.np/blob/809a5f18f6c1ef0fb7113b43969f4da66177d0d2/llama3.py#L17), you could clip the magnitude of the inputs to the sigmoid function as in my NumPy CLIP implementation: https://github.com/99991/NumPyCLIP/blob/main/numpyclip.py#L113-L116

I'd also recommend to store the weights somewhere else (for example as a release or on HuggingFace) and download them on demand, because GitHub has really low bandwidth quota.

I very much appreciate your shape annotations. They make understanding much easier. Great work!

**Comment by likejazz** [comment]
Thank you to your suggestions!

1. This implementation is not focused on performance, but your suggestion of a `heap` structure is appreciated. I'll be sure to incorporate it in the future.
2. I used to `set_printoptions()` to disable scientific notation to make it more readable. I used it to debug the values, but I don't use it anymore, so I removed it.
3. I uploaded the model directly to GitHub for convenience. The file size was 85MB, so it wasn't too big. But in general, your suggestion is correct.

**Comment by 99991** [comment]
2. Oh, you are right. I was mistaken and thought the code said something different. Nevermind!
3. I had a similarly large project in the past and GitHub would frequently block downloads whenever the quota of just 5 GB was exceeded. But I agree, it is more convenient this way.
